const images = {
  bg : require("../../../assets/images/bg.png"),
  bg_dark : require("../../../assets/images/bg_dark.png"),
  doc : require("../../../assets/images/doc.png"),
  bg_1 : require("../../../assets/images/bg_1.png"),
  work : require("../../../assets/images/work.png"),
  featured_bg_image : require("../../../assets/images/featured_bg_image.png"),
  mobile_image : require("../../../assets/images/mobile_image.png"),
  modeling_image : require("../../../assets/images/modeling_image.png"),
  web_designing_image : require("../../../assets/images/web_designing_image.png"),
  illustration_image : require("../../../assets/images/illustration_image.png"),
  drawing_image : require("../../../assets/images/drawing_image.png"),
  animation_image : require("../../../assets/images/animation_image.png"),
  pdf : require("../../../assets/images/pdf.png"),
  profile : require("../../../assets/images/profile.png"),
  sketch : require("../../../assets/images/sketch.png"),
  start_learning : require("../../../assets/images/start_learning.png"),
  student_1 : require("../../../assets/images/student_1.png"),
  student_3 : require("../../../assets/images/student_3.png"),
  thumbnail_1 : require("../../../assets/images/thumbnail_1.png"),
  thumbnail_2 : require("../../../assets/images/thumbnail_2.png"),
  thumbnail_3 : require("../../../assets/images/thumbnail_3.png"),
  thumbnail_4 : require("../../../assets/images/thumbnail_4.png"),
  loadingImage : require("../../../assets/images/loading-image.gif"),
  thubnailDefault: require("../../../assets/images/thumbnail_default.jpg"),
  video_default_url: require("../../../assets/images/big_buck_bunny.mp4"),
};

export default images;